name: Testes de Unidade em um projeto NodeJS e Fastify
 
on:
  push:
    branches: [ main ]

jobs:
  test-unities:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Usar Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Instalar dependencias  
        run: npm install
      - name: Build
        run: npm run build
      - name: Rodar os testes de unidade com JEST 
        run: npm test    




